# Generated by Django 5.1.4 on 2024-12-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='account_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('superadmin', 'Superadmin'), ('user', 'User'), ('editor', 'Editor'), ('moderator', 'Moderator')], default='admin', max_length=10),
        ),
    ]
