# Generated by Django 5.1.1 on 2024-10-27 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('date_entered', models.DateField()),
                ('birthday', models.DateField()),
                ('age_in_months', models.PositiveIntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight_for_age_status', models.CharField(choices=[('UW', 'Underweight'), ('ST', 'Stunted'), ('N', 'Normal'), ('SEVUW', 'Severely Underweight'), ('MW', 'Moderately Well')], max_length=5)),
                ('height_for_age_status', models.CharField(choices=[('UW', 'Underweight'), ('ST', 'Stunted'), ('N', 'Normal'), ('SEVUW', 'Severely Underweight'), ('MW', 'Moderately Well')], max_length=5)),
                ('weight_for_lt_ht_status', models.CharField(choices=[('UW', 'Underweight'), ('ST', 'Stunted'), ('N', 'Normal'), ('SEVUW', 'Severely Underweight'), ('MW', 'Moderately Well')], max_length=5)),
                ('child_image', models.ImageField(blank=True, null=True, upload_to='child_images/')),
            ],
        ),
        migrations.CreateModel(
            name='MaternalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Pregnant', 'Pregnant'), ('Lactating', 'Lactating')], max_length=20)),
                ('date_entered', models.DateTimeField(auto_now_add=True)),
                ('birthday', models.DateField()),
                ('age', models.PositiveIntegerField()),
                ('muac', models.CharField(max_length=50)),
                ('nutritional_status', models.CharField(choices=[('Normal', 'Normal'), ('Overweight', 'Overweight'), ('Underweight', 'Underweight')], max_length=20)),
                ('four_ps_member', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('image', models.ImageField(blank=True, null=True, upload_to='maternal_records/')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(default='src/images/user.png', upload_to='profile_pics/')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
